[tool.poetry]
name = "battleship"
version = "0.1.0"
description = "Play Battleship The Game in your terminal."
authors = ["Roman Vlasenko <klavionik@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
websockets = "^11.0.3"
rich = "^13.5.2"
loguru = "^0.7.0"
pyee = "^11.0.0"
textual = "^0.40.0"
blacksheep = "^1.2.18"
uvicorn = "^0.23.2"
httpx = "^0.25.0"
pydantic = "^2.4.2"
pydantic-settings = "^2.0.3"
pyjwt = {extras = ["crypto"], version = "^2.8.0"}
uvloop = "^0.19.0"
email-validator = "^2.1.0.post1"
auth0-python = "^4.5.0"
typer = "^0.9.0"

[tool.poetry.scripts]
battleship = "battleship.tui.app:run"
battleship-cli = "battleship.cli:app"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.mypy]
plugins = [
  "pydantic.mypy"
]

[tool.poetry.group.dev.dependencies]
mypy = "^1.5.0"
coverage = "^7.3.0"
watchdog = {extras = ["watchmedo"], version = "^3.0.0"}
textual-dev = "^1.1.0"
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
