# https://taskfile.dev

version: '3'

tasks:
  install: poetry install --all-extras
  test: pytest
  mypy: mypy --strict battleship
  coverage: coverage run -m pytest
  cov-report:
    cmds:
      - task: coverage
      - coverage html
      - python -m webbrowser -t htmlcov/index.html
  app:dev: poetry run textual run --dev battleship.cli
  server:dev: poetry run uvicorn --reload --factory battleship.server:create_app
  server:export: poetry export --output requirements-server.txt --only=main --extras=server --without-hashes
  release:
    cmds:
      - poetry version {{.CLI_ARGS}}
      - git add pyproject.toml
      - git commit -m "Bump client version to $(poetry version --short)"
      - git tag "client/$(poetry version --short)"
      - task: install
