# https://taskfile.dev

version: '3'

tasks:
  install: poetry install --all-extras
  mypy: mypy --strict battleship
  coverage: coverage run -m pytest
  cov-report:
    cmds:
      - task: coverage
      - coverage html
      - python -m webbrowser -t htmlcov/index.html
  server:dev: poetry run uvicorn --reload --factory battleship.server:create_app
  server:export: poetry export --output requirements-server.txt --only=main --extras=server --without-hashes
  server:release-*:
    vars:
      current_version:
        sh: basename $(git describe --tags --match="server/[0-9]*" --abbrev=0 HEAD)
      part: "{{index .MATCH 0}}"
    cmd: git tag "server/$(pysemver bump {{.part}} {{.current_version}})"
  client:dev: poetry run textual run --dev battleship.cli:run
  client:release-*:
    vars:
      part: "{{index .MATCH 0}}"
    cmds:
      - poetry version {{.part}}
      - git add pyproject.toml
      - git commit -m "Bump client version to $(poetry version --short)"
      - git tag "client/$(poetry version --short)"
      - task: install
  client:logs:
    vars:
      source:
        # Get the filename of the latest client log.
        sh: ls -r | grep -e client_.*\.log | head -n 1
    cmd: tail -f {{.source}}
  load: poetry run python tools/load_testing/load.py --server-url http://0.0.0.0:9090 --users-file {{.CLI_ARGS}}
