# https://taskfile.dev

version: '3'

tasks:
  test: pytest
  mypy: mypy --strict battleship
  coverage: coverage run -m pytest
  cov-report:
    cmds:
      - task: coverage
      - coverage html
      - python -m webbrowser -t htmlcov/index.html
  app:dev: poetry run textual run --dev battleship.cli
  server:dev: poetry run uvicorn --reload --factory battleship.server:create_app
