name: Release client
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - "client/*"

env:
  POETRY_VERSION: "1.4.2"

jobs:
  release:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install poetry==${{ env.POETRY_VERSION }}
      - run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_PROJECT_TOKEN }}
